name: pytorch
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py37_0
  - cffi=1.11.5=py37he75722e_1
  - cycler=0.10.0=py_1
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.2=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.5=hf484d3e_1002
  - fontconfig=2.13.1=h2176d3f_1000
  - freetype=2.9.1=h8a8886c_1
  - gettext=0.19.8.1=h9745a5d_1001
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=hb3b607b_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jedi=0.13.2=py37_0
  - jinja2=2.10=py37_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - kiwisolver=1.0.1=py37h6bb024c_1002
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h14c3975_1004
  - libpng=1.6.36=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - markupsafe=1.1.0=py37h7b6447c_0
  - matplotlib=3.0.2=py37_1002
  - matplotlib-base=3.0.2=py37h167e16e_1002
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - nbconvert=5.3.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py37h6bb024c_1
  - notebook=5.7.4=py37_0
  - numpy=1.15.4=py37h7e9f1db_0
  - numpy-base=1.15.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.2=py37_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=5.4.1=py37h34e0f95_0
  - pip=19.0.1=py37_0
  - pot=0.5.1=py37h637b7d7_1000
  - prometheus_client=0.5.0=py37_0
  - prompt_toolkit=2.0.8=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.3.1=py37_0
  - pyparsing=2.3.1=py_0
  - pyqt=5.6.0=py37h13b7fb3_1008
  - python=3.7.2=h0371630_0
  - python-dateutil=2.8.0=py_0
  - pytorch-cpu=1.0.1=py3.7_cpu_2
  - pyzmq=17.1.2=py37he6710b0_2
  - qt=5.6.3=h8bf5577_3
  - qtconsole=4.4.3=py37_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.2=py37hd81dba3_0
  - scipy=1.2.1=py37h7c811a0_0
  - send2trash=1.5.0=py37_0
  - setuptools=40.8.0=py37_0
  - sip=4.18.1=py37hf484d3e_1000
  - six=1.12.0=py37_0
  - sqlite=3.26.0=h7b6447c_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.9=h84994c4_1000
  - torchvision-cpu=0.2.1=py_2
  - tornado=5.1.1=py37h14c3975_1000
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.2=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0

